# This is an example mods.toml file.
# Any fields that aren't annotated with #optional are *required*!
modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPLv3" # Want to make your mod open source? Check out https://choosealicense.com/!

# This is a URL to e.g. your GitHub or CurseForge issues page.
# It will appear in any crash reports this mod is directly involved in.
# issueTrackerURL="https://github.com/invalid/pleasechangeme/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]]
    modId = "gregitas_core"
    # The version number of the mod - unlike in the Forge MDK,
    # we'll use the processResources task to replace this for us
    version = "${version}"
    displayName = "Gravitas² Core Mod"
    # This URL will be queried by the Forge update checker in order to find the latest version of your mod.
    # If an update is found, you'll see a little blinking "emerald" symbol on your Mods button!
    # updateJSONURL="https://changeme.dev/updates.json" #optional
    # This is your mod's "homepage" and will be displayed on the mod's information screen in the Mods panel.
    # displayURL="https://changeme.dev/" #optional
    # This will be displayed as your mod's logo in the Mods panel.
    # logoFile="icon.png" #optional
    # Some more fluff displayed in the Mods panel. Feel free to issue your special thanks here!
    # credits="Thanks to Mojang for making this great game" #optional
    # Some more fluff displayed in the Mods panel. Plug your stuff here!
    authors="Screret" #optional
    # A multi-line description for your mod. This has no minimum length, but it *is* required!
    description = '''
    Core Mod for Gravitas².
    '''

    [[dependencies.gregitas_core]]
        modId = "forge"
        mandatory = true
        versionRange = "[47,)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies.gregitas_core]]
        modId = "minecraft"
        mandatory = true
        versionRange = "[1.20.1,)"
        ordering = "NONE"
        side = "BOTH"

    [[dependencies.gregitas_core]]
        modId = "gtceu"
        mandatory = true
        versionRange = "[1.1.3.b]"
        ordering = "AFTER"
        side = "BOTH"

    [[dependencies.gregitas_core]]
        modId = "tfc"
        mandatory = true
        versionRange = "[3.1.0-beta,)"
        ordering = "AFTER"
        side = "BOTH"

    [[dependencies.gregitas_core]]
        modId = "railways"
        mandatory = true
        versionRange = "1.5.3+forge-mc1.20.1"
        ordering = "AFTER"
        side = "BOTH"